# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Título')),
                ('decricao', models.TextField(verbose_name='Texto')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
            ],
        ),
    ]
